### ISSUE TITLE
No dots in the background

### ISSUE THREAD

**Issue by RainSharky** [stdword/logseq-bujo-theme#8]
After updating to the newest version, the dots in the background are no longer visable:

![image](https://github.com/stdword/logseq-bujo-theme/assets/125542081/de0f0bfc-6acb-402d-bd49-c8d67ed80846)

**Logseq Version:** 0.10.0
**Theme Version:** 1.1.0

### Installed Plugins:
![image](https://github.com/stdword/logseq-bujo-theme/assets/125542081/1077d734-bfb4-40f7-a6c2-eda02186acc3)

### Content of custom.css:
```css
:root * {
  font-family: Cascadia Code, monospace;
  font-variant-ligatures: none !important;
}
```
